// <auto-generated />
using System;
using Ecommerce.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ecommerce.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220510053744_seeddata-khachhang")]
    partial class seeddatakhachhang
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ecommerce.Entities.Account", b =>
                {
                    b.Property<int>("AcccountID")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassWord")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("salt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AcccountID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Ecommerce.Entities.Category", b =>
                {
                    b.Property<int>("CateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CateName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Levels")
                        .HasColumnType("int");

                    b.Property<string>("MetaDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordering")
                        .HasColumnType("int");

                    b.Property<string>("Parent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<string>("Thumb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CateID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Ecommerce.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Active = false,
                            Address = "Đồng Nai",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 5, 10, 12, 37, 43, 647, DateTimeKind.Local).AddTicks(6129),
                            Email = "Kh1@email.com",
                            FullName = "Khách Hàng 1",
                            LastLogin = new DateTime(2022, 5, 10, 12, 37, 43, 648, DateTimeKind.Local).AddTicks(9169),
                            PassWord = "123",
                            Phone = "000000000"
                        },
                        new
                        {
                            CustomerID = 2,
                            Active = false,
                            Address = "Đồng Nai",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1337),
                            Email = "Kh2@email.com",
                            FullName = "Khách Hàng 2",
                            LastLogin = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1343),
                            PassWord = "123",
                            Phone = "000000000"
                        },
                        new
                        {
                            CustomerID = 3,
                            Active = false,
                            Address = "Đồng Nai",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1347),
                            Email = "Kh3@email.com",
                            FullName = "Khách Hàng 3",
                            LastLogin = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1348),
                            PassWord = "123",
                            Phone = "000000000"
                        },
                        new
                        {
                            CustomerID = 4,
                            Active = false,
                            Address = "Đồng Nai",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1350),
                            Email = "Kh4@email.com",
                            FullName = "Khách Hàng 4",
                            LastLogin = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1351),
                            PassWord = "123",
                            Phone = "000000000"
                        },
                        new
                        {
                            CustomerID = 5,
                            Active = false,
                            Address = "Đồng Nai",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1352),
                            Email = "Kh5@email.com",
                            FullName = "Khách Hàng 5",
                            LastLogin = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1354),
                            PassWord = "123",
                            Phone = "000000000"
                        },
                        new
                        {
                            CustomerID = 6,
                            Active = false,
                            Address = "Đồng Nai",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1355),
                            Email = "Kh5@email.com",
                            FullName = "Khách Hàng 6",
                            LastLogin = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1356),
                            PassWord = "123",
                            Phone = "000000000"
                        },
                        new
                        {
                            CustomerID = 7,
                            Active = false,
                            Address = "Đồng Nai",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1362),
                            Email = "Kh5@email.com",
                            FullName = "Khách Hàng 7",
                            LastLogin = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1363),
                            PassWord = "123",
                            Phone = "000000000"
                        },
                        new
                        {
                            CustomerID = 8,
                            Active = false,
                            Address = "Đồng Nai",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1364),
                            Email = "Kh5@email.com",
                            FullName = "Khách Hàng 8",
                            LastLogin = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1365),
                            PassWord = "123",
                            Phone = "000000000"
                        },
                        new
                        {
                            CustomerID = 9,
                            Active = false,
                            Address = "Đồng Nai",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1368),
                            Email = "Kh5@email.com",
                            FullName = "Khách Hàng 9",
                            LastLogin = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1369),
                            PassWord = "123",
                            Phone = "000000000"
                        },
                        new
                        {
                            CustomerID = 10,
                            Active = false,
                            Address = "Đồng Nai",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1370),
                            Email = "Kh5@email.com",
                            FullName = "Khách Hàng 10",
                            LastLogin = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1371),
                            PassWord = "123",
                            Phone = "000000000"
                        },
                        new
                        {
                            CustomerID = 11,
                            Active = false,
                            Address = "Đồng Nai",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1373),
                            Email = "Kh5@email.com",
                            FullName = "Khách Hàng 11",
                            LastLogin = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1374),
                            PassWord = "123",
                            Phone = "000000000"
                        },
                        new
                        {
                            CustomerID = 12,
                            Active = false,
                            Address = "Đồng Nai",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1375),
                            Email = "Kh5@email.com",
                            FullName = "Khách Hàng 12",
                            LastLogin = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1377),
                            PassWord = "123",
                            Phone = "000000000"
                        },
                        new
                        {
                            CustomerID = 13,
                            Active = false,
                            Address = "Đồng Nai",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1378),
                            Email = "Kh5@email.com",
                            FullName = "Khách Hàng 13",
                            LastLogin = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1379),
                            PassWord = "123",
                            Phone = "000000000"
                        },
                        new
                        {
                            CustomerID = 14,
                            Active = false,
                            Address = "Đồng Nai",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1380),
                            Email = "Kh5@email.com",
                            FullName = "Khách Hàng 14",
                            LastLogin = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1381),
                            PassWord = "123",
                            Phone = "000000000"
                        },
                        new
                        {
                            CustomerID = 15,
                            Active = false,
                            Address = "Đồng Nai",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1383),
                            Email = "Kh5@email.com",
                            FullName = "Khách Hàng 15",
                            LastLogin = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1384),
                            PassWord = "123",
                            Phone = "000000000"
                        },
                        new
                        {
                            CustomerID = 16,
                            Active = false,
                            Address = "Đồng Nai",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1386),
                            Email = "Kh5@email.com",
                            FullName = "Khách Hàng 16",
                            LastLogin = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1387),
                            PassWord = "123",
                            Phone = "000000000"
                        },
                        new
                        {
                            CustomerID = 17,
                            Active = false,
                            Address = "Đồng Nai",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1388),
                            Email = "Kh5@email.com",
                            FullName = "Khách Hàng 17",
                            LastLogin = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1389),
                            PassWord = "123",
                            Phone = "000000000"
                        },
                        new
                        {
                            CustomerID = 18,
                            Active = false,
                            Address = "Đồng Nai",
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1391),
                            Email = "Kh5@email.com",
                            FullName = "Khách Hàng 18",
                            LastLogin = new DateTime(2022, 5, 10, 12, 37, 43, 649, DateTimeKind.Local).AddTicks(1392),
                            PassWord = "123",
                            Phone = "000000000"
                        });
                });

            modelBuilder.Entity("Ecommerce.Entities.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PaidPaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("PaymentID")
                        .HasColumnType("float");

                    b.Property<DateTime>("ShipDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalMoney")
                        .HasColumnType("float");

                    b.Property<int?>("TransactSatatusID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("TransactSatatusID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Ecommerce.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("TotalMoney")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailID");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Ecommerce.Entities.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BestSellers")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<bool>("HomeFlag")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDDescriptionesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitsInStock")
                        .HasColumnType("int");

                    b.Property<string>("Video")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Ecommerce.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            Description = "Administrator",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            Description = "Nhân Viên",
                            RoleName = "Staff"
                        });
                });

            modelBuilder.Entity("Ecommerce.Entities.TransactSatatus", b =>
                {
                    b.Property<int>("TransactSatatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactSatatusID");

                    b.ToTable("TransactSatatus");
                });

            modelBuilder.Entity("Ecommerce.Entities.Account", b =>
                {
                    b.HasOne("Ecommerce.Entities.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("AcccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Ecommerce.Entities.Order", b =>
                {
                    b.HasOne("Ecommerce.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID");

                    b.HasOne("Ecommerce.Entities.TransactSatatus", "TransactSatatus")
                        .WithMany("Orders")
                        .HasForeignKey("TransactSatatusID");

                    b.Navigation("Customer");

                    b.Navigation("TransactSatatus");
                });

            modelBuilder.Entity("Ecommerce.Entities.OrderDetail", b =>
                {
                    b.HasOne("Ecommerce.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderDetailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Ecommerce.Entities.Product", b =>
                {
                    b.HasOne("Ecommerce.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ecommerce.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Ecommerce.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Ecommerce.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Ecommerce.Entities.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Ecommerce.Entities.TransactSatatus", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
